### ISSUE TITLE
Please point me to a working release

### ISSUE THREAD

**Issue by teowave** [totaljs/uibuilder#1]
Dear Totaljs team

We have been trying to run locally the uibuilder, installed it according to the instructions, it doesnt seem to work. It requests Total 5, in the config files there is Total 4, changing it to 5 did not seem to work either.

Anyway, I would be grateful for a pointer to a working version, so we can try it out

Best regards

**Comment by JamesHusband** [comment]
I ran into the same isssue: 

`Error: Cannot find module '/home/jam/Development/uibuilder/node_modules/total5/index.js'. Please verify that the package.json has a valid "main" entry` 

debugging the error shows that the total5 package is empty, I am guessing an issue with the publish the NPM. Workaround I found was to install total5 directly from the github repo:

`npm i totaljs/framework5`

**Comment by petersirka** [comment]
Sorry guys, we have a mistake in `package.json`... I have fixed it, so update the `package.json` file only. Let us know if you have any other problems. Join Total.js Telegram: https://t.me/totaljs
