### ISSUE TITLE
IFrame redenering not working

### ISSUE THREAD

**Issue by irshadmb** [totaljs/uibuilder#3]
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Load URL in iFrame</title>
    <style>
        body, html {
            height: 100%;
            margin: 0;
        }
        iframe {
            width: 100%;
            height: 100%;
            border: none;
        }
    </style>
</head>
<body>
    <iframe src="https://uibuilder.totaljs.com/" allow="accelerometer; gyroscope"></iframe>

</body>
</html>
Simple IFrame to embed in my test application. It is not working. Can you please guide me.

**Comment by petersirka** [comment]
Check this example: 
[uibuilder-iframe.html.zip](https://github.com/user-attachments/files/16659308/uibuilder-iframe.html.zip)

- extract it
- open it in your web browser

__IMPORTANT__: the example uses our CDN version.

**Comment by irshadmb** [comment]
Thanks @petersirka , It worked.
